name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/danny-avila/LibreChat.git # 替换为上游仓库的URL
        git fetch upstream
        git checkout -B main upstream/main # 强制重置主分支到上游仓库的主分支
        git push -f origin main # 强制推送更新到你的主分支
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
